// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: delay_event.proto

package transit

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DelayEvent_EventType int32

const (
	DelayEvent_ARRIVAL_DELAY   DelayEvent_EventType = 0
	DelayEvent_DEPARTURE_DELAY DelayEvent_EventType = 1
	DelayEvent_TRIP_CANCELLED  DelayEvent_EventType = 2
	DelayEvent_SKIP_STOP       DelayEvent_EventType = 3
)

// Enum value maps for DelayEvent_EventType.
var (
	DelayEvent_EventType_name = map[int32]string{
		0: "ARRIVAL_DELAY",
		1: "DEPARTURE_DELAY",
		2: "TRIP_CANCELLED",
		3: "SKIP_STOP",
	}
	DelayEvent_EventType_value = map[string]int32{
		"ARRIVAL_DELAY":   0,
		"DEPARTURE_DELAY": 1,
		"TRIP_CANCELLED":  2,
		"SKIP_STOP":       3,
	}
)

func (x DelayEvent_EventType) Enum() *DelayEvent_EventType {
	p := new(DelayEvent_EventType)
	*p = x
	return p
}

func (x DelayEvent_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DelayEvent_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_delay_event_proto_enumTypes[0].Descriptor()
}

func (DelayEvent_EventType) Type() protoreflect.EnumType {
	return &file_delay_event_proto_enumTypes[0]
}

func (x DelayEvent_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DelayEvent_EventType.Descriptor instead.
func (DelayEvent_EventType) EnumDescriptor() ([]byte, []int) {
	return file_delay_event_proto_rawDescGZIP(), []int{0, 0}
}

type DelayEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AgencyId         string                 `protobuf:"bytes,1,opt,name=agency_id,json=agencyId,proto3" json:"agency_id,omitempty"`
	TripId           string                 `protobuf:"bytes,2,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	RouteId          string                 `protobuf:"bytes,3,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	StopId           string                 `protobuf:"bytes,4,opt,name=stop_id,json=stopId,proto3" json:"stop_id,omitempty"`
	DelaySeconds     int32                  `protobuf:"varint,5,opt,name=delay_seconds,json=delaySeconds,proto3" json:"delay_seconds,omitempty"`
	ObservedAt       int64                  `protobuf:"varint,6,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	ScheduledArrival int64                  `protobuf:"varint,7,opt,name=scheduled_arrival,json=scheduledArrival,proto3" json:"scheduled_arrival,omitempty"`
	PredictedArrival int64                  `protobuf:"varint,8,opt,name=predicted_arrival,json=predictedArrival,proto3" json:"predicted_arrival,omitempty"`
	Type             DelayEvent_EventType   `protobuf:"varint,9,opt,name=type,proto3,enum=transit.DelayEvent_EventType" json:"type,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DelayEvent) Reset() {
	*x = DelayEvent{}
	mi := &file_delay_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelayEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelayEvent) ProtoMessage() {}

func (x *DelayEvent) ProtoReflect() protoreflect.Message {
	mi := &file_delay_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelayEvent.ProtoReflect.Descriptor instead.
func (*DelayEvent) Descriptor() ([]byte, []int) {
	return file_delay_event_proto_rawDescGZIP(), []int{0}
}

func (x *DelayEvent) GetAgencyId() string {
	if x != nil {
		return x.AgencyId
	}
	return ""
}

func (x *DelayEvent) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *DelayEvent) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *DelayEvent) GetStopId() string {
	if x != nil {
		return x.StopId
	}
	return ""
}

func (x *DelayEvent) GetDelaySeconds() int32 {
	if x != nil {
		return x.DelaySeconds
	}
	return 0
}

func (x *DelayEvent) GetObservedAt() int64 {
	if x != nil {
		return x.ObservedAt
	}
	return 0
}

func (x *DelayEvent) GetScheduledArrival() int64 {
	if x != nil {
		return x.ScheduledArrival
	}
	return 0
}

func (x *DelayEvent) GetPredictedArrival() int64 {
	if x != nil {
		return x.PredictedArrival
	}
	return 0
}

func (x *DelayEvent) GetType() DelayEvent_EventType {
	if x != nil {
		return x.Type
	}
	return DelayEvent_ARRIVAL_DELAY
}

type DelayEventBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*DelayEvent          `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelayEventBatch) Reset() {
	*x = DelayEventBatch{}
	mi := &file_delay_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelayEventBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelayEventBatch) ProtoMessage() {}

func (x *DelayEventBatch) ProtoReflect() protoreflect.Message {
	mi := &file_delay_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelayEventBatch.ProtoReflect.Descriptor instead.
func (*DelayEventBatch) Descriptor() ([]byte, []int) {
	return file_delay_event_proto_rawDescGZIP(), []int{1}
}

func (x *DelayEventBatch) GetEvents() []*DelayEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_delay_event_proto protoreflect.FileDescriptor

const file_delay_event_proto_rawDesc = "" +
	"\n" +
	"\x11delay_event.proto\x12\atransit\"\xa1\x03\n" +
	"\n" +
	"DelayEvent\x12\x1b\n" +
	"\tagency_id\x18\x01 \x01(\tR\bagencyId\x12\x17\n" +
	"\atrip_id\x18\x02 \x01(\tR\x06tripId\x12\x19\n" +
	"\broute_id\x18\x03 \x01(\tR\arouteId\x12\x17\n" +
	"\astop_id\x18\x04 \x01(\tR\x06stopId\x12#\n" +
	"\rdelay_seconds\x18\x05 \x01(\x05R\fdelaySeconds\x12\x1f\n" +
	"\vobserved_at\x18\x06 \x01(\x03R\n" +
	"observedAt\x12+\n" +
	"\x11scheduled_arrival\x18\a \x01(\x03R\x10scheduledArrival\x12+\n" +
	"\x11predicted_arrival\x18\b \x01(\x03R\x10predictedArrival\x121\n" +
	"\x04type\x18\t \x01(\x0e2\x1d.transit.DelayEvent.EventTypeR\x04type\"V\n" +
	"\tEventType\x12\x11\n" +
	"\rARRIVAL_DELAY\x10\x00\x12\x13\n" +
	"\x0fDEPARTURE_DELAY\x10\x01\x12\x12\n" +
	"\x0eTRIP_CANCELLED\x10\x02\x12\r\n" +
	"\tSKIP_STOP\x10\x03\">\n" +
	"\x0fDelayEventBatch\x12+\n" +
	"\x06events\x18\x01 \x03(\v2\x13.transit.DelayEventR\x06eventsB3Z1github.com/briankim06/urban-goggles/proto/transitb\x06proto3"

var (
	file_delay_event_proto_rawDescOnce sync.Once
	file_delay_event_proto_rawDescData []byte
)

func file_delay_event_proto_rawDescGZIP() []byte {
	file_delay_event_proto_rawDescOnce.Do(func() {
		file_delay_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_delay_event_proto_rawDesc), len(file_delay_event_proto_rawDesc)))
	})
	return file_delay_event_proto_rawDescData
}

var file_delay_event_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_delay_event_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_delay_event_proto_goTypes = []any{
	(DelayEvent_EventType)(0), // 0: transit.DelayEvent.EventType
	(*DelayEvent)(nil),        // 1: transit.DelayEvent
	(*DelayEventBatch)(nil),   // 2: transit.DelayEventBatch
}
var file_delay_event_proto_depIdxs = []int32{
	0, // 0: transit.DelayEvent.type:type_name -> transit.DelayEvent.EventType
	1, // 1: transit.DelayEventBatch.events:type_name -> transit.DelayEvent
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_delay_event_proto_init() }
func file_delay_event_proto_init() {
	if File_delay_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_delay_event_proto_rawDesc), len(file_delay_event_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_delay_event_proto_goTypes,
		DependencyIndexes: file_delay_event_proto_depIdxs,
		EnumInfos:         file_delay_event_proto_enumTypes,
		MessageInfos:      file_delay_event_proto_msgTypes,
	}.Build()
	File_delay_event_proto = out.File
	file_delay_event_proto_goTypes = nil
	file_delay_event_proto_depIdxs = nil
}
