// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: propagation.proto

package transit

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransferImpact_ImpactLevel int32

const (
	TransferImpact_AT_RISK TransferImpact_ImpactLevel = 0
	TransferImpact_BROKEN  TransferImpact_ImpactLevel = 1
)

// Enum value maps for TransferImpact_ImpactLevel.
var (
	TransferImpact_ImpactLevel_name = map[int32]string{
		0: "AT_RISK",
		1: "BROKEN",
	}
	TransferImpact_ImpactLevel_value = map[string]int32{
		"AT_RISK": 0,
		"BROKEN":  1,
	}
)

func (x TransferImpact_ImpactLevel) Enum() *TransferImpact_ImpactLevel {
	p := new(TransferImpact_ImpactLevel)
	*p = x
	return p
}

func (x TransferImpact_ImpactLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransferImpact_ImpactLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_propagation_proto_enumTypes[0].Descriptor()
}

func (TransferImpact_ImpactLevel) Type() protoreflect.EnumType {
	return &file_propagation_proto_enumTypes[0]
}

func (x TransferImpact_ImpactLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransferImpact_ImpactLevel.Descriptor instead.
func (TransferImpact_ImpactLevel) EnumDescriptor() ([]byte, []int) {
	return file_propagation_proto_rawDescGZIP(), []int{0, 0}
}

type TransferImpact struct {
	state                         protoimpl.MessageState     `protogen:"open.v1"`
	FromTripId                    string                     `protobuf:"bytes,1,opt,name=from_trip_id,json=fromTripId,proto3" json:"from_trip_id,omitempty"`
	FromRouteId                   string                     `protobuf:"bytes,2,opt,name=from_route_id,json=fromRouteId,proto3" json:"from_route_id,omitempty"`
	ToRouteId                     string                     `protobuf:"bytes,3,opt,name=to_route_id,json=toRouteId,proto3" json:"to_route_id,omitempty"`
	StationId                     string                     `protobuf:"bytes,4,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"`
	SourceDelaySeconds            int32                      `protobuf:"varint,5,opt,name=source_delay_seconds,json=sourceDelaySeconds,proto3" json:"source_delay_seconds,omitempty"`
	OriginalTransferMarginSeconds int32                      `protobuf:"varint,6,opt,name=original_transfer_margin_seconds,json=originalTransferMarginSeconds,proto3" json:"original_transfer_margin_seconds,omitempty"`
	RemainingMarginSeconds        int32                      `protobuf:"varint,7,opt,name=remaining_margin_seconds,json=remainingMarginSeconds,proto3" json:"remaining_margin_seconds,omitempty"`
	Level                         TransferImpact_ImpactLevel `protobuf:"varint,8,opt,name=level,proto3,enum=transit.TransferImpact_ImpactLevel" json:"level,omitempty"`
	DetectedAt                    int64                      `protobuf:"varint,9,opt,name=detected_at,json=detectedAt,proto3" json:"detected_at,omitempty"`
	NextViableTripId              string                     `protobuf:"bytes,10,opt,name=next_viable_trip_id,json=nextViableTripId,proto3" json:"next_viable_trip_id,omitempty"`
	AdditionalWaitSeconds         int32                      `protobuf:"varint,11,opt,name=additional_wait_seconds,json=additionalWaitSeconds,proto3" json:"additional_wait_seconds,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *TransferImpact) Reset() {
	*x = TransferImpact{}
	mi := &file_propagation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferImpact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferImpact) ProtoMessage() {}

func (x *TransferImpact) ProtoReflect() protoreflect.Message {
	mi := &file_propagation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferImpact.ProtoReflect.Descriptor instead.
func (*TransferImpact) Descriptor() ([]byte, []int) {
	return file_propagation_proto_rawDescGZIP(), []int{0}
}

func (x *TransferImpact) GetFromTripId() string {
	if x != nil {
		return x.FromTripId
	}
	return ""
}

func (x *TransferImpact) GetFromRouteId() string {
	if x != nil {
		return x.FromRouteId
	}
	return ""
}

func (x *TransferImpact) GetToRouteId() string {
	if x != nil {
		return x.ToRouteId
	}
	return ""
}

func (x *TransferImpact) GetStationId() string {
	if x != nil {
		return x.StationId
	}
	return ""
}

func (x *TransferImpact) GetSourceDelaySeconds() int32 {
	if x != nil {
		return x.SourceDelaySeconds
	}
	return 0
}

func (x *TransferImpact) GetOriginalTransferMarginSeconds() int32 {
	if x != nil {
		return x.OriginalTransferMarginSeconds
	}
	return 0
}

func (x *TransferImpact) GetRemainingMarginSeconds() int32 {
	if x != nil {
		return x.RemainingMarginSeconds
	}
	return 0
}

func (x *TransferImpact) GetLevel() TransferImpact_ImpactLevel {
	if x != nil {
		return x.Level
	}
	return TransferImpact_AT_RISK
}

func (x *TransferImpact) GetDetectedAt() int64 {
	if x != nil {
		return x.DetectedAt
	}
	return 0
}

func (x *TransferImpact) GetNextViableTripId() string {
	if x != nil {
		return x.NextViableTripId
	}
	return ""
}

func (x *TransferImpact) GetAdditionalWaitSeconds() int32 {
	if x != nil {
		return x.AdditionalWaitSeconds
	}
	return 0
}

type PropagationResult struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SourceTripId       string                 `protobuf:"bytes,1,opt,name=source_trip_id,json=sourceTripId,proto3" json:"source_trip_id,omitempty"`
	SourceStopId       string                 `protobuf:"bytes,2,opt,name=source_stop_id,json=sourceStopId,proto3" json:"source_stop_id,omitempty"`
	SourceDelaySeconds int32                  `protobuf:"varint,3,opt,name=source_delay_seconds,json=sourceDelaySeconds,proto3" json:"source_delay_seconds,omitempty"`
	Impacts            []*DownstreamImpact    `protobuf:"bytes,4,rep,name=impacts,proto3" json:"impacts,omitempty"`
	ComputedAt         int64                  `protobuf:"varint,5,opt,name=computed_at,json=computedAt,proto3" json:"computed_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PropagationResult) Reset() {
	*x = PropagationResult{}
	mi := &file_propagation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropagationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropagationResult) ProtoMessage() {}

func (x *PropagationResult) ProtoReflect() protoreflect.Message {
	mi := &file_propagation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropagationResult.ProtoReflect.Descriptor instead.
func (*PropagationResult) Descriptor() ([]byte, []int) {
	return file_propagation_proto_rawDescGZIP(), []int{1}
}

func (x *PropagationResult) GetSourceTripId() string {
	if x != nil {
		return x.SourceTripId
	}
	return ""
}

func (x *PropagationResult) GetSourceStopId() string {
	if x != nil {
		return x.SourceStopId
	}
	return ""
}

func (x *PropagationResult) GetSourceDelaySeconds() int32 {
	if x != nil {
		return x.SourceDelaySeconds
	}
	return 0
}

func (x *PropagationResult) GetImpacts() []*DownstreamImpact {
	if x != nil {
		return x.Impacts
	}
	return nil
}

func (x *PropagationResult) GetComputedAt() int64 {
	if x != nil {
		return x.ComputedAt
	}
	return 0
}

type DownstreamImpact struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	RouteId                  string                 `protobuf:"bytes,1,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	StopId                   string                 `protobuf:"bytes,2,opt,name=stop_id,json=stopId,proto3" json:"stop_id,omitempty"`
	PredictedAdditionalDelay int32                  `protobuf:"varint,3,opt,name=predicted_additional_delay,json=predictedAdditionalDelay,proto3" json:"predicted_additional_delay,omitempty"`
	Confidence               float32                `protobuf:"fixed32,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	HopsFromSource           int32                  `protobuf:"varint,5,opt,name=hops_from_source,json=hopsFromSource,proto3" json:"hops_from_source,omitempty"`
	ImpactType               string                 `protobuf:"bytes,6,opt,name=impact_type,json=impactType,proto3" json:"impact_type,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *DownstreamImpact) Reset() {
	*x = DownstreamImpact{}
	mi := &file_propagation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownstreamImpact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownstreamImpact) ProtoMessage() {}

func (x *DownstreamImpact) ProtoReflect() protoreflect.Message {
	mi := &file_propagation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownstreamImpact.ProtoReflect.Descriptor instead.
func (*DownstreamImpact) Descriptor() ([]byte, []int) {
	return file_propagation_proto_rawDescGZIP(), []int{2}
}

func (x *DownstreamImpact) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *DownstreamImpact) GetStopId() string {
	if x != nil {
		return x.StopId
	}
	return ""
}

func (x *DownstreamImpact) GetPredictedAdditionalDelay() int32 {
	if x != nil {
		return x.PredictedAdditionalDelay
	}
	return 0
}

func (x *DownstreamImpact) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *DownstreamImpact) GetHopsFromSource() int32 {
	if x != nil {
		return x.HopsFromSource
	}
	return 0
}

func (x *DownstreamImpact) GetImpactType() string {
	if x != nil {
		return x.ImpactType
	}
	return ""
}

var File_propagation_proto protoreflect.FileDescriptor

const file_propagation_proto_rawDesc = "" +
	"\n" +
	"\x11propagation.proto\x12\atransit\"\xb5\x04\n" +
	"\x0eTransferImpact\x12 \n" +
	"\ffrom_trip_id\x18\x01 \x01(\tR\n" +
	"fromTripId\x12\"\n" +
	"\rfrom_route_id\x18\x02 \x01(\tR\vfromRouteId\x12\x1e\n" +
	"\vto_route_id\x18\x03 \x01(\tR\ttoRouteId\x12\x1d\n" +
	"\n" +
	"station_id\x18\x04 \x01(\tR\tstationId\x120\n" +
	"\x14source_delay_seconds\x18\x05 \x01(\x05R\x12sourceDelaySeconds\x12G\n" +
	" original_transfer_margin_seconds\x18\x06 \x01(\x05R\x1doriginalTransferMarginSeconds\x128\n" +
	"\x18remaining_margin_seconds\x18\a \x01(\x05R\x16remainingMarginSeconds\x129\n" +
	"\x05level\x18\b \x01(\x0e2#.transit.TransferImpact.ImpactLevelR\x05level\x12\x1f\n" +
	"\vdetected_at\x18\t \x01(\x03R\n" +
	"detectedAt\x12-\n" +
	"\x13next_viable_trip_id\x18\n" +
	" \x01(\tR\x10nextViableTripId\x126\n" +
	"\x17additional_wait_seconds\x18\v \x01(\x05R\x15additionalWaitSeconds\"&\n" +
	"\vImpactLevel\x12\v\n" +
	"\aAT_RISK\x10\x00\x12\n" +
	"\n" +
	"\x06BROKEN\x10\x01\"\xe7\x01\n" +
	"\x11PropagationResult\x12$\n" +
	"\x0esource_trip_id\x18\x01 \x01(\tR\fsourceTripId\x12$\n" +
	"\x0esource_stop_id\x18\x02 \x01(\tR\fsourceStopId\x120\n" +
	"\x14source_delay_seconds\x18\x03 \x01(\x05R\x12sourceDelaySeconds\x123\n" +
	"\aimpacts\x18\x04 \x03(\v2\x19.transit.DownstreamImpactR\aimpacts\x12\x1f\n" +
	"\vcomputed_at\x18\x05 \x01(\x03R\n" +
	"computedAt\"\xef\x01\n" +
	"\x10DownstreamImpact\x12\x19\n" +
	"\broute_id\x18\x01 \x01(\tR\arouteId\x12\x17\n" +
	"\astop_id\x18\x02 \x01(\tR\x06stopId\x12<\n" +
	"\x1apredicted_additional_delay\x18\x03 \x01(\x05R\x18predictedAdditionalDelay\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x02R\n" +
	"confidence\x12(\n" +
	"\x10hops_from_source\x18\x05 \x01(\x05R\x0ehopsFromSource\x12\x1f\n" +
	"\vimpact_type\x18\x06 \x01(\tR\n" +
	"impactTypeB3Z1github.com/briankim06/urban-goggles/proto/transitb\x06proto3"

var (
	file_propagation_proto_rawDescOnce sync.Once
	file_propagation_proto_rawDescData []byte
)

func file_propagation_proto_rawDescGZIP() []byte {
	file_propagation_proto_rawDescOnce.Do(func() {
		file_propagation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_propagation_proto_rawDesc), len(file_propagation_proto_rawDesc)))
	})
	return file_propagation_proto_rawDescData
}

var file_propagation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_propagation_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_propagation_proto_goTypes = []any{
	(TransferImpact_ImpactLevel)(0), // 0: transit.TransferImpact.ImpactLevel
	(*TransferImpact)(nil),          // 1: transit.TransferImpact
	(*PropagationResult)(nil),       // 2: transit.PropagationResult
	(*DownstreamImpact)(nil),        // 3: transit.DownstreamImpact
}
var file_propagation_proto_depIdxs = []int32{
	0, // 0: transit.TransferImpact.level:type_name -> transit.TransferImpact.ImpactLevel
	3, // 1: transit.PropagationResult.impacts:type_name -> transit.DownstreamImpact
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_propagation_proto_init() }
func file_propagation_proto_init() {
	if File_propagation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_propagation_proto_rawDesc), len(file_propagation_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_propagation_proto_goTypes,
		DependencyIndexes: file_propagation_proto_depIdxs,
		EnumInfos:         file_propagation_proto_enumTypes,
		MessageInfos:      file_propagation_proto_msgTypes,
	}.Build()
	File_propagation_proto = out.File
	file_propagation_proto_goTypes = nil
	file_propagation_proto_depIdxs = nil
}
