// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: service.proto

package transit

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TransitPropagation_GetNetworkState_FullMethodName        = "/transit.TransitPropagation/GetNetworkState"
	TransitPropagation_GetRouteDelays_FullMethodName         = "/transit.TransitPropagation/GetRouteDelays"
	TransitPropagation_PredictImpact_FullMethodName          = "/transit.TransitPropagation/PredictImpact"
	TransitPropagation_GetBlastRadius_FullMethodName         = "/transit.TransitPropagation/GetBlastRadius"
	TransitPropagation_GetTransferReliability_FullMethodName = "/transit.TransitPropagation/GetTransferReliability"
	TransitPropagation_StreamAlerts_FullMethodName           = "/transit.TransitPropagation/StreamAlerts"
)

// TransitPropagationClient is the client API for TransitPropagation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransitPropagationClient interface {
	GetNetworkState(ctx context.Context, in *NetworkStateRequest, opts ...grpc.CallOption) (*NetworkStateResponse, error)
	GetRouteDelays(ctx context.Context, in *RouteDelaysRequest, opts ...grpc.CallOption) (*RouteDelaysResponse, error)
	PredictImpact(ctx context.Context, in *PredictImpactRequest, opts ...grpc.CallOption) (*PropagationResult, error)
	GetBlastRadius(ctx context.Context, in *BlastRadiusRequest, opts ...grpc.CallOption) (*BlastRadiusResponse, error)
	GetTransferReliability(ctx context.Context, in *TransferReliabilityRequest, opts ...grpc.CallOption) (*TransferReliabilityResponse, error)
	StreamAlerts(ctx context.Context, in *StreamAlertsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TransferImpact], error)
}

type transitPropagationClient struct {
	cc grpc.ClientConnInterface
}

func NewTransitPropagationClient(cc grpc.ClientConnInterface) TransitPropagationClient {
	return &transitPropagationClient{cc}
}

func (c *transitPropagationClient) GetNetworkState(ctx context.Context, in *NetworkStateRequest, opts ...grpc.CallOption) (*NetworkStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NetworkStateResponse)
	err := c.cc.Invoke(ctx, TransitPropagation_GetNetworkState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transitPropagationClient) GetRouteDelays(ctx context.Context, in *RouteDelaysRequest, opts ...grpc.CallOption) (*RouteDelaysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RouteDelaysResponse)
	err := c.cc.Invoke(ctx, TransitPropagation_GetRouteDelays_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transitPropagationClient) PredictImpact(ctx context.Context, in *PredictImpactRequest, opts ...grpc.CallOption) (*PropagationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PropagationResult)
	err := c.cc.Invoke(ctx, TransitPropagation_PredictImpact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transitPropagationClient) GetBlastRadius(ctx context.Context, in *BlastRadiusRequest, opts ...grpc.CallOption) (*BlastRadiusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlastRadiusResponse)
	err := c.cc.Invoke(ctx, TransitPropagation_GetBlastRadius_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transitPropagationClient) GetTransferReliability(ctx context.Context, in *TransferReliabilityRequest, opts ...grpc.CallOption) (*TransferReliabilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferReliabilityResponse)
	err := c.cc.Invoke(ctx, TransitPropagation_GetTransferReliability_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transitPropagationClient) StreamAlerts(ctx context.Context, in *StreamAlertsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TransferImpact], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TransitPropagation_ServiceDesc.Streams[0], TransitPropagation_StreamAlerts_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamAlertsRequest, TransferImpact]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TransitPropagation_StreamAlertsClient = grpc.ServerStreamingClient[TransferImpact]

// TransitPropagationServer is the server API for TransitPropagation service.
// All implementations must embed UnimplementedTransitPropagationServer
// for forward compatibility.
type TransitPropagationServer interface {
	GetNetworkState(context.Context, *NetworkStateRequest) (*NetworkStateResponse, error)
	GetRouteDelays(context.Context, *RouteDelaysRequest) (*RouteDelaysResponse, error)
	PredictImpact(context.Context, *PredictImpactRequest) (*PropagationResult, error)
	GetBlastRadius(context.Context, *BlastRadiusRequest) (*BlastRadiusResponse, error)
	GetTransferReliability(context.Context, *TransferReliabilityRequest) (*TransferReliabilityResponse, error)
	StreamAlerts(*StreamAlertsRequest, grpc.ServerStreamingServer[TransferImpact]) error
	mustEmbedUnimplementedTransitPropagationServer()
}

// UnimplementedTransitPropagationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTransitPropagationServer struct{}

func (UnimplementedTransitPropagationServer) GetNetworkState(context.Context, *NetworkStateRequest) (*NetworkStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNetworkState not implemented")
}
func (UnimplementedTransitPropagationServer) GetRouteDelays(context.Context, *RouteDelaysRequest) (*RouteDelaysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRouteDelays not implemented")
}
func (UnimplementedTransitPropagationServer) PredictImpact(context.Context, *PredictImpactRequest) (*PropagationResult, error) {
	return nil, status.Error(codes.Unimplemented, "method PredictImpact not implemented")
}
func (UnimplementedTransitPropagationServer) GetBlastRadius(context.Context, *BlastRadiusRequest) (*BlastRadiusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBlastRadius not implemented")
}
func (UnimplementedTransitPropagationServer) GetTransferReliability(context.Context, *TransferReliabilityRequest) (*TransferReliabilityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTransferReliability not implemented")
}
func (UnimplementedTransitPropagationServer) StreamAlerts(*StreamAlertsRequest, grpc.ServerStreamingServer[TransferImpact]) error {
	return status.Error(codes.Unimplemented, "method StreamAlerts not implemented")
}
func (UnimplementedTransitPropagationServer) mustEmbedUnimplementedTransitPropagationServer() {}
func (UnimplementedTransitPropagationServer) testEmbeddedByValue()                            {}

// UnsafeTransitPropagationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransitPropagationServer will
// result in compilation errors.
type UnsafeTransitPropagationServer interface {
	mustEmbedUnimplementedTransitPropagationServer()
}

func RegisterTransitPropagationServer(s grpc.ServiceRegistrar, srv TransitPropagationServer) {
	// If the following call panics, it indicates UnimplementedTransitPropagationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TransitPropagation_ServiceDesc, srv)
}

func _TransitPropagation_GetNetworkState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransitPropagationServer).GetNetworkState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransitPropagation_GetNetworkState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransitPropagationServer).GetNetworkState(ctx, req.(*NetworkStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransitPropagation_GetRouteDelays_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteDelaysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransitPropagationServer).GetRouteDelays(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransitPropagation_GetRouteDelays_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransitPropagationServer).GetRouteDelays(ctx, req.(*RouteDelaysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransitPropagation_PredictImpact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PredictImpactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransitPropagationServer).PredictImpact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransitPropagation_PredictImpact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransitPropagationServer).PredictImpact(ctx, req.(*PredictImpactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransitPropagation_GetBlastRadius_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlastRadiusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransitPropagationServer).GetBlastRadius(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransitPropagation_GetBlastRadius_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransitPropagationServer).GetBlastRadius(ctx, req.(*BlastRadiusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransitPropagation_GetTransferReliability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferReliabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransitPropagationServer).GetTransferReliability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransitPropagation_GetTransferReliability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransitPropagationServer).GetTransferReliability(ctx, req.(*TransferReliabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransitPropagation_StreamAlerts_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamAlertsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TransitPropagationServer).StreamAlerts(m, &grpc.GenericServerStream[StreamAlertsRequest, TransferImpact]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TransitPropagation_StreamAlertsServer = grpc.ServerStreamingServer[TransferImpact]

// TransitPropagation_ServiceDesc is the grpc.ServiceDesc for TransitPropagation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransitPropagation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "transit.TransitPropagation",
	HandlerType: (*TransitPropagationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNetworkState",
			Handler:    _TransitPropagation_GetNetworkState_Handler,
		},
		{
			MethodName: "GetRouteDelays",
			Handler:    _TransitPropagation_GetRouteDelays_Handler,
		},
		{
			MethodName: "PredictImpact",
			Handler:    _TransitPropagation_PredictImpact_Handler,
		},
		{
			MethodName: "GetBlastRadius",
			Handler:    _TransitPropagation_GetBlastRadius_Handler,
		},
		{
			MethodName: "GetTransferReliability",
			Handler:    _TransitPropagation_GetTransferReliability_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamAlerts",
			Handler:       _TransitPropagation_StreamAlerts_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "service.proto",
}
