// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: service.proto

package transit

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NetworkStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkStateRequest) Reset() {
	*x = NetworkStateRequest{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkStateRequest) ProtoMessage() {}

func (x *NetworkStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkStateRequest.ProtoReflect.Descriptor instead.
func (*NetworkStateRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

type NetworkStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Routes        map[string]*RouteState `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	AsOf          int64                  `protobuf:"varint,2,opt,name=as_of,json=asOf,proto3" json:"as_of,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkStateResponse) Reset() {
	*x = NetworkStateResponse{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkStateResponse) ProtoMessage() {}

func (x *NetworkStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkStateResponse.ProtoReflect.Descriptor instead.
func (*NetworkStateResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *NetworkStateResponse) GetRoutes() map[string]*RouteState {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *NetworkStateResponse) GetAsOf() int64 {
	if x != nil {
		return x.AsOf
	}
	return 0
}

type RouteState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouteId       string                 `protobuf:"bytes,1,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	Delays        []*StopDelay           `protobuf:"bytes,2,rep,name=delays,proto3" json:"delays,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteState) Reset() {
	*x = RouteState{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteState) ProtoMessage() {}

func (x *RouteState) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteState.ProtoReflect.Descriptor instead.
func (*RouteState) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *RouteState) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *RouteState) GetDelays() []*StopDelay {
	if x != nil {
		return x.Delays
	}
	return nil
}

type StopDelay struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StopId        string                 `protobuf:"bytes,1,opt,name=stop_id,json=stopId,proto3" json:"stop_id,omitempty"`
	StopName      string                 `protobuf:"bytes,2,opt,name=stop_name,json=stopName,proto3" json:"stop_name,omitempty"`
	DelaySeconds  int32                  `protobuf:"varint,3,opt,name=delay_seconds,json=delaySeconds,proto3" json:"delay_seconds,omitempty"`
	Confidence    float32                `protobuf:"fixed32,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopDelay) Reset() {
	*x = StopDelay{}
	mi := &file_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopDelay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopDelay) ProtoMessage() {}

func (x *StopDelay) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopDelay.ProtoReflect.Descriptor instead.
func (*StopDelay) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3}
}

func (x *StopDelay) GetStopId() string {
	if x != nil {
		return x.StopId
	}
	return ""
}

func (x *StopDelay) GetStopName() string {
	if x != nil {
		return x.StopName
	}
	return ""
}

func (x *StopDelay) GetDelaySeconds() int32 {
	if x != nil {
		return x.DelaySeconds
	}
	return 0
}

func (x *StopDelay) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

type RouteDelaysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouteId       string                 `protobuf:"bytes,1,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteDelaysRequest) Reset() {
	*x = RouteDelaysRequest{}
	mi := &file_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteDelaysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteDelaysRequest) ProtoMessage() {}

func (x *RouteDelaysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteDelaysRequest.ProtoReflect.Descriptor instead.
func (*RouteDelaysRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{4}
}

func (x *RouteDelaysRequest) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

type RouteDelaysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delays        []*StopDelay           `protobuf:"bytes,1,rep,name=delays,proto3" json:"delays,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteDelaysResponse) Reset() {
	*x = RouteDelaysResponse{}
	mi := &file_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteDelaysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteDelaysResponse) ProtoMessage() {}

func (x *RouteDelaysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteDelaysResponse.ProtoReflect.Descriptor instead.
func (*RouteDelaysResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{5}
}

func (x *RouteDelaysResponse) GetDelays() []*StopDelay {
	if x != nil {
		return x.Delays
	}
	return nil
}

type PredictImpactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	StopId        string                 `protobuf:"bytes,2,opt,name=stop_id,json=stopId,proto3" json:"stop_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictImpactRequest) Reset() {
	*x = PredictImpactRequest{}
	mi := &file_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictImpactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictImpactRequest) ProtoMessage() {}

func (x *PredictImpactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictImpactRequest.ProtoReflect.Descriptor instead.
func (*PredictImpactRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{6}
}

func (x *PredictImpactRequest) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *PredictImpactRequest) GetStopId() string {
	if x != nil {
		return x.StopId
	}
	return ""
}

type BlastRadiusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StationId     string                 `protobuf:"bytes,1,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlastRadiusRequest) Reset() {
	*x = BlastRadiusRequest{}
	mi := &file_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlastRadiusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlastRadiusRequest) ProtoMessage() {}

func (x *BlastRadiusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlastRadiusRequest.ProtoReflect.Descriptor instead.
func (*BlastRadiusRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{7}
}

func (x *BlastRadiusRequest) GetStationId() string {
	if x != nil {
		return x.StationId
	}
	return ""
}

type BlastRadiusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cascades      []*PropagationResult   `protobuf:"bytes,1,rep,name=cascades,proto3" json:"cascades,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlastRadiusResponse) Reset() {
	*x = BlastRadiusResponse{}
	mi := &file_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlastRadiusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlastRadiusResponse) ProtoMessage() {}

func (x *BlastRadiusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlastRadiusResponse.ProtoReflect.Descriptor instead.
func (*BlastRadiusResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{8}
}

func (x *BlastRadiusResponse) GetCascades() []*PropagationResult {
	if x != nil {
		return x.Cascades
	}
	return nil
}

type TransferReliabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StationId     string                 `protobuf:"bytes,1,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"`
	HourOfDay     int32                  `protobuf:"varint,2,opt,name=hour_of_day,json=hourOfDay,proto3" json:"hour_of_day,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferReliabilityRequest) Reset() {
	*x = TransferReliabilityRequest{}
	mi := &file_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferReliabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferReliabilityRequest) ProtoMessage() {}

func (x *TransferReliabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferReliabilityRequest.ProtoReflect.Descriptor instead.
func (*TransferReliabilityRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{9}
}

func (x *TransferReliabilityRequest) GetStationId() string {
	if x != nil {
		return x.StationId
	}
	return ""
}

func (x *TransferReliabilityRequest) GetHourOfDay() int32 {
	if x != nil {
		return x.HourOfDay
	}
	return 0
}

type TransferReliabilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transfers     []*TransferStats       `protobuf:"bytes,1,rep,name=transfers,proto3" json:"transfers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferReliabilityResponse) Reset() {
	*x = TransferReliabilityResponse{}
	mi := &file_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferReliabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferReliabilityResponse) ProtoMessage() {}

func (x *TransferReliabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferReliabilityResponse.ProtoReflect.Descriptor instead.
func (*TransferReliabilityResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{10}
}

func (x *TransferReliabilityResponse) GetTransfers() []*TransferStats {
	if x != nil {
		return x.Transfers
	}
	return nil
}

type TransferStats struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	FromRouteId        string                 `protobuf:"bytes,1,opt,name=from_route_id,json=fromRouteId,proto3" json:"from_route_id,omitempty"`
	ToRouteId          string                 `protobuf:"bytes,2,opt,name=to_route_id,json=toRouteId,proto3" json:"to_route_id,omitempty"`
	StationId          string                 `protobuf:"bytes,3,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"`
	ReliabilityPct     float32                `protobuf:"fixed32,4,opt,name=reliability_pct,json=reliabilityPct,proto3" json:"reliability_pct,omitempty"`
	AvgDelayWhenBroken float32                `protobuf:"fixed32,5,opt,name=avg_delay_when_broken,json=avgDelayWhenBroken,proto3" json:"avg_delay_when_broken,omitempty"`
	SampleCount        int32                  `protobuf:"varint,6,opt,name=sample_count,json=sampleCount,proto3" json:"sample_count,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TransferStats) Reset() {
	*x = TransferStats{}
	mi := &file_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferStats) ProtoMessage() {}

func (x *TransferStats) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferStats.ProtoReflect.Descriptor instead.
func (*TransferStats) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{11}
}

func (x *TransferStats) GetFromRouteId() string {
	if x != nil {
		return x.FromRouteId
	}
	return ""
}

func (x *TransferStats) GetToRouteId() string {
	if x != nil {
		return x.ToRouteId
	}
	return ""
}

func (x *TransferStats) GetStationId() string {
	if x != nil {
		return x.StationId
	}
	return ""
}

func (x *TransferStats) GetReliabilityPct() float32 {
	if x != nil {
		return x.ReliabilityPct
	}
	return 0
}

func (x *TransferStats) GetAvgDelayWhenBroken() float32 {
	if x != nil {
		return x.AvgDelayWhenBroken
	}
	return 0
}

func (x *TransferStats) GetSampleCount() int32 {
	if x != nil {
		return x.SampleCount
	}
	return 0
}

type StreamAlertsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouteIds      []string               `protobuf:"bytes,1,rep,name=route_ids,json=routeIds,proto3" json:"route_ids,omitempty"`
	StationIds    []string               `protobuf:"bytes,2,rep,name=station_ids,json=stationIds,proto3" json:"station_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamAlertsRequest) Reset() {
	*x = StreamAlertsRequest{}
	mi := &file_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAlertsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAlertsRequest) ProtoMessage() {}

func (x *StreamAlertsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAlertsRequest.ProtoReflect.Descriptor instead.
func (*StreamAlertsRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{12}
}

func (x *StreamAlertsRequest) GetRouteIds() []string {
	if x != nil {
		return x.RouteIds
	}
	return nil
}

func (x *StreamAlertsRequest) GetStationIds() []string {
	if x != nil {
		return x.StationIds
	}
	return nil
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\atransit\x1a\x11propagation.proto\"\x15\n" +
	"\x13NetworkStateRequest\"\xbe\x01\n" +
	"\x14NetworkStateResponse\x12A\n" +
	"\x06routes\x18\x01 \x03(\v2).transit.NetworkStateResponse.RoutesEntryR\x06routes\x12\x13\n" +
	"\x05as_of\x18\x02 \x01(\x03R\x04asOf\x1aN\n" +
	"\vRoutesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.transit.RouteStateR\x05value:\x028\x01\"S\n" +
	"\n" +
	"RouteState\x12\x19\n" +
	"\broute_id\x18\x01 \x01(\tR\arouteId\x12*\n" +
	"\x06delays\x18\x02 \x03(\v2\x12.transit.StopDelayR\x06delays\"\x86\x01\n" +
	"\tStopDelay\x12\x17\n" +
	"\astop_id\x18\x01 \x01(\tR\x06stopId\x12\x1b\n" +
	"\tstop_name\x18\x02 \x01(\tR\bstopName\x12#\n" +
	"\rdelay_seconds\x18\x03 \x01(\x05R\fdelaySeconds\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x02R\n" +
	"confidence\"/\n" +
	"\x12RouteDelaysRequest\x12\x19\n" +
	"\broute_id\x18\x01 \x01(\tR\arouteId\"A\n" +
	"\x13RouteDelaysResponse\x12*\n" +
	"\x06delays\x18\x01 \x03(\v2\x12.transit.StopDelayR\x06delays\"H\n" +
	"\x14PredictImpactRequest\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\x12\x17\n" +
	"\astop_id\x18\x02 \x01(\tR\x06stopId\"3\n" +
	"\x12BlastRadiusRequest\x12\x1d\n" +
	"\n" +
	"station_id\x18\x01 \x01(\tR\tstationId\"M\n" +
	"\x13BlastRadiusResponse\x126\n" +
	"\bcascades\x18\x01 \x03(\v2\x1a.transit.PropagationResultR\bcascades\"[\n" +
	"\x1aTransferReliabilityRequest\x12\x1d\n" +
	"\n" +
	"station_id\x18\x01 \x01(\tR\tstationId\x12\x1e\n" +
	"\vhour_of_day\x18\x02 \x01(\x05R\thourOfDay\"S\n" +
	"\x1bTransferReliabilityResponse\x124\n" +
	"\ttransfers\x18\x01 \x03(\v2\x16.transit.TransferStatsR\ttransfers\"\xf1\x01\n" +
	"\rTransferStats\x12\"\n" +
	"\rfrom_route_id\x18\x01 \x01(\tR\vfromRouteId\x12\x1e\n" +
	"\vto_route_id\x18\x02 \x01(\tR\ttoRouteId\x12\x1d\n" +
	"\n" +
	"station_id\x18\x03 \x01(\tR\tstationId\x12'\n" +
	"\x0freliability_pct\x18\x04 \x01(\x02R\x0ereliabilityPct\x121\n" +
	"\x15avg_delay_when_broken\x18\x05 \x01(\x02R\x12avgDelayWhenBroken\x12!\n" +
	"\fsample_count\x18\x06 \x01(\x05R\vsampleCount\"S\n" +
	"\x13StreamAlertsRequest\x12\x1b\n" +
	"\troute_ids\x18\x01 \x03(\tR\brouteIds\x12\x1f\n" +
	"\vstation_ids\x18\x02 \x03(\tR\n" +
	"stationIds2\xf8\x03\n" +
	"\x12TransitPropagation\x12N\n" +
	"\x0fGetNetworkState\x12\x1c.transit.NetworkStateRequest\x1a\x1d.transit.NetworkStateResponse\x12K\n" +
	"\x0eGetRouteDelays\x12\x1b.transit.RouteDelaysRequest\x1a\x1c.transit.RouteDelaysResponse\x12J\n" +
	"\rPredictImpact\x12\x1d.transit.PredictImpactRequest\x1a\x1a.transit.PropagationResult\x12K\n" +
	"\x0eGetBlastRadius\x12\x1b.transit.BlastRadiusRequest\x1a\x1c.transit.BlastRadiusResponse\x12c\n" +
	"\x16GetTransferReliability\x12#.transit.TransferReliabilityRequest\x1a$.transit.TransferReliabilityResponse\x12G\n" +
	"\fStreamAlerts\x12\x1c.transit.StreamAlertsRequest\x1a\x17.transit.TransferImpact0\x01B3Z1github.com/briankim06/urban-goggles/proto/transitb\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_service_proto_goTypes = []any{
	(*NetworkStateRequest)(nil),         // 0: transit.NetworkStateRequest
	(*NetworkStateResponse)(nil),        // 1: transit.NetworkStateResponse
	(*RouteState)(nil),                  // 2: transit.RouteState
	(*StopDelay)(nil),                   // 3: transit.StopDelay
	(*RouteDelaysRequest)(nil),          // 4: transit.RouteDelaysRequest
	(*RouteDelaysResponse)(nil),         // 5: transit.RouteDelaysResponse
	(*PredictImpactRequest)(nil),        // 6: transit.PredictImpactRequest
	(*BlastRadiusRequest)(nil),          // 7: transit.BlastRadiusRequest
	(*BlastRadiusResponse)(nil),         // 8: transit.BlastRadiusResponse
	(*TransferReliabilityRequest)(nil),  // 9: transit.TransferReliabilityRequest
	(*TransferReliabilityResponse)(nil), // 10: transit.TransferReliabilityResponse
	(*TransferStats)(nil),               // 11: transit.TransferStats
	(*StreamAlertsRequest)(nil),         // 12: transit.StreamAlertsRequest
	nil,                                 // 13: transit.NetworkStateResponse.RoutesEntry
	(*PropagationResult)(nil),           // 14: transit.PropagationResult
	(*TransferImpact)(nil),              // 15: transit.TransferImpact
}
var file_service_proto_depIdxs = []int32{
	13, // 0: transit.NetworkStateResponse.routes:type_name -> transit.NetworkStateResponse.RoutesEntry
	3,  // 1: transit.RouteState.delays:type_name -> transit.StopDelay
	3,  // 2: transit.RouteDelaysResponse.delays:type_name -> transit.StopDelay
	14, // 3: transit.BlastRadiusResponse.cascades:type_name -> transit.PropagationResult
	11, // 4: transit.TransferReliabilityResponse.transfers:type_name -> transit.TransferStats
	2,  // 5: transit.NetworkStateResponse.RoutesEntry.value:type_name -> transit.RouteState
	0,  // 6: transit.TransitPropagation.GetNetworkState:input_type -> transit.NetworkStateRequest
	4,  // 7: transit.TransitPropagation.GetRouteDelays:input_type -> transit.RouteDelaysRequest
	6,  // 8: transit.TransitPropagation.PredictImpact:input_type -> transit.PredictImpactRequest
	7,  // 9: transit.TransitPropagation.GetBlastRadius:input_type -> transit.BlastRadiusRequest
	9,  // 10: transit.TransitPropagation.GetTransferReliability:input_type -> transit.TransferReliabilityRequest
	12, // 11: transit.TransitPropagation.StreamAlerts:input_type -> transit.StreamAlertsRequest
	1,  // 12: transit.TransitPropagation.GetNetworkState:output_type -> transit.NetworkStateResponse
	5,  // 13: transit.TransitPropagation.GetRouteDelays:output_type -> transit.RouteDelaysResponse
	14, // 14: transit.TransitPropagation.PredictImpact:output_type -> transit.PropagationResult
	8,  // 15: transit.TransitPropagation.GetBlastRadius:output_type -> transit.BlastRadiusResponse
	10, // 16: transit.TransitPropagation.GetTransferReliability:output_type -> transit.TransferReliabilityResponse
	15, // 17: transit.TransitPropagation.StreamAlerts:output_type -> transit.TransferImpact
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_propagation_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
